### ISSUE TITLE
TypeError: Cannot read property 'L' of undefined

### ISSUE THREAD

**Issue by Chitrank-Dixit** [tomtom-international/tomtom-use-case-react-js-integration#1]
Hello Tomtom developers,

I am trying to integrate tomtom maps in my react project, so I first tried this one but it is not running and saying "TypeError: Cannot read property 'L' of undefined"

<img width="1050" alt="screen shot 2018-10-29 at 6 42 39 pm" src="https://user-images.githubusercontent.com/1781313/47651900-7645a880-dbaa-11e8-9b68-68495f055fb8.png">

**Comment by yasircs4** [comment]
I have same issue

**Comment by yasircs4** [comment]
There step that i miss.
in _Getting Started_  number **2**
you have  to download `TomTom Web SDK` the from [https://developer.tomtom.com/maps-sdk-web/downloads](url)
and Unpack it to `'\public\sdk' `

**Comment by szogoon** [comment]
Yes, the SDK is needed here because it provides the tomtom object.
@Chitrank-Dixit - did you add tomtom.min.js to scripts?
